name = "RES"
uuid = "deea43f6-e04c-4128-8155-98bf06a2bcbd"
authors = ["Florian Oswald <florian.oswald@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
